name: limetv
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # fonts:
    # - family: PlusJakartaSans
    #   fonts:
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-ExtraBold.ttf
    #       weight: 800
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-Bold.ttf
    #       weight: 700
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-SemiBold.ttf
    #       weight: 600
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-Medium.ttf
    #       weight: 500
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-Regular.ttf
    #       weight: 400
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-Light.ttf
    #       weight: 300
    #     - asset: fonts/plus_jakarta_display/PlusJakartaSans-ExtraLight.ttf
    #       weight: 200
        
    # - family: ClashDisplay
    #   fonts:
    #     - asset: fonts/clash/ClashDisplay-Medium.otf
    #       weight: 500
    #     - asset: fonts/clash/ClashDisplay-Regular.otf
    #       weight: 400
          
    # - family: HeliosExtC
    #   fonts:
    #     - asset: fonts/HeliosExtC-Regular.otf
    #       weight: 400

# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/logo.png

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/logo.png"
#   min_sdk_android: 21
