import 'package:limetv/data/models/category_model.dart';
import 'package:limetv/data/models/movie_model.dart';

import 'assets.dart';

String settingsMainWidgetText =
    'Оставьте контактные данные для получения уведомлений \nот сервиса и взаимодействия со службой поддержки.';

String bottomAboutText =
    "© 2023 LimeTV. 18+\nФедеральные каналы доступны для бесплатного просмотра круглосуточно\nHBO ® and related service marks are the property of Home Box Office, Inc\nООО «LIMETVUZ», адрес местонахождения: 115035, Узбекистан, г. Ташкент, ул. Садовническая, д. 82, стр. 2, пом. 9А01\nАдрес для обращений пользователей: info@limetv.uz";

List<MovieModel> bannerMovies = [
  MovieModel(
    bgImage: Assets.images.banner1,
    mainImage: Assets.images.kingman,
    name: "King’s Man: Начало",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about:
        "После принятия образа аватара солдат Джейк Салли становится предводителем народа на'ви и берет на себя миссию по защите новых друзей от корыстных бизнесменов с Земли. Теперь ему есть за кого бороться — с Джейком его прекрасная возлюбленная Нейтири. Когда на Пандору возвращаются до зубов вооруженные земляне, Джейк готов дать им отпор",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.banner1,
    mainImage: Assets.images.kingman,
    name: "King’s Man: Начало",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about:
        "После принятия образа аватара солдат Джейк Салли становится предводителем народа на'ви и берет на себя миссию по защите новых друзей от корыстных бизнесменов с Земли. Теперь ему есть за кого бороться — с Джейком его прекрасная возлюбленная Нейтири. Когда на Пандору возвращаются до зубов вооруженные земляне, Джейк готов дать им отпор",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.banner1,
    mainImage: Assets.images.kingman,
    name: "King’s Man: Начало",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about:
        "После принятия образа аватара солдат Джейк Салли становится предводителем народа на'ви и берет на себя миссию по защите новых друзей от корыстных бизнесменов с Земли. Теперь ему есть за кого бороться — с Джейком его прекрасная возлюбленная Нейтири. Когда на Пандору возвращаются до зубов вооруженные земляне, Джейк готов дать им отпор",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.banner1,
    mainImage: Assets.images.kingman,
    name: "King’s Man: Начало",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about:
        "После принятия образа аватара солдат Джейк Салли становится предводителем народа на'ви и берет на себя миссию по защите новых друзей от корыстных бизнесменов с Земли. Теперь ему есть за кого бороться — с Джейком его прекрасная возлюбленная Нейтири. Когда на Пандору возвращаются до зубов вооруженные земляне, Джейк готов дать им отпор",
    rating: "IMDB 8.6",
  ),
];

List<MovieModel> continueWatchingMovies = [
  MovieModel(
    bgImage: Assets.images.deathCar,
    mainImage: Assets.images.deathCar,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.titanic2,
    mainImage: Assets.images.titanic2,
    name: "Титаник",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.indianaJones,
    mainImage: Assets.images.indianaJones,
    name: "Indiana Jones",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.deathCar,
    mainImage: Assets.images.deathCar,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.titanic2,
    mainImage: Assets.images.titanic2,
    name: "Титаник",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.indianaJones,
    mainImage: Assets.images.indianaJones,
    name: "Indiana Jones",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];

List<MovieModel> skoroVKino = [
  MovieModel(
    bgImage: Assets.images.avatar,
    mainImage: Assets.images.avatar,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.blade,
    mainImage: Assets.images.blade,
    name: "Титаник",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.fantasticFour,
    mainImage: Assets.images.fantasticFour,
    name: "Indiana Jones",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mermaid,
    mainImage: Assets.images.mermaid,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.avatar,
    mainImage: Assets.images.avatar,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.blade,
    mainImage: Assets.images.blade,
    name: "Титаник",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.fantasticFour,
    mainImage: Assets.images.fantasticFour,
    name: "Indiana Jones",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mermaid,
    mainImage: Assets.images.mermaid,
    name: "Смертоносные машины",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];
List<MovieModel> subscriptionMovies = [
  MovieModel(
    bgImage: Assets.images.christmas,
    mainImage: Assets.images.christmas,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.lastChristmas,
    mainImage: Assets.images.lastChristmas,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.christmasVacation,
    mainImage: Assets.images.christmasVacation,
    name: "Christmas Vacation",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.christmasChronicles,
    mainImage: Assets.images.christmasChronicles,
    name: "Сhristmas Chronicles",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];
List<MovieModel> filmy = [
  MovieModel(
    bgImage: Assets.images.princePersea,
    mainImage: Assets.images.princePersea,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.love,
    mainImage: Assets.images.love,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.ripd,
    mainImage: Assets.images.ripd,
    name: "Christmas Vacation",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.assasin,
    mainImage: Assets.images.assasin,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.love,
    mainImage: Assets.images.love,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.ripd,
    mainImage: Assets.images.ripd,
    name: "Christmas Vacation",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];
List<MovieModel> serialy = [
  MovieModel(
    bgImage: Assets.images.gothamKnights,
    mainImage: Assets.images.gothamKnights,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.breakingBad,
    mainImage: Assets.images.breakingBad,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mandalorian,
    mainImage: Assets.images.mandalorian,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.gothamKnights,
    mainImage: Assets.images.gothamKnights,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.breakingBad,
    mainImage: Assets.images.breakingBad,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mandalorian,
    mainImage: Assets.images.mandalorian,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];

List<CategoryModel> categories = [
  CategoryModel(categoryIcon: Assets.icons.documentary, categoryName: "Биографии", categoryMovieCount: 1334),
  CategoryModel(categoryIcon: Assets.icons.action, categoryName: "Боевики", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.filmNoir, categoryName: "Детективы", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.drama, categoryName: "Драмы", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.comedy, categoryName: "Комедии", categoryMovieCount: 1334),
  CategoryModel(categoryIcon: Assets.icons.crime, categoryName: "Криминалы", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.romantic, categoryName: "Мелодрамы", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.musical, categoryName: "Мюзиклы", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.sport, categoryName: "Спорт", categoryMovieCount: 500),
  CategoryModel(categoryIcon: Assets.icons.fantasy, categoryName: "Фантастики", categoryMovieCount: 1334),
  CategoryModel(categoryIcon: Assets.icons.horror, categoryName: "Триллеры", categoryMovieCount: 44534),
  CategoryModel(categoryIcon: Assets.icons.thriller, categoryName: "Ужасы", categoryMovieCount: 44534),
];

List<String> janrs = [
  'Комедия',
  'Драма',
  'Мелодрама',
  'Ужас',
  'Триллер',
  'Криминал',
  'Фантастика',
  'Боевик',
  'Детектив',
  'Аниме',
  'Мултьфильм',
  'Приключения',
  'Фентези',
  'Исторический',
  'Семейный',
  'Биография',
  'Мистика'
];



List<MovieModel> englishMovies = [
  MovieModel(
    bgImage: Assets.images.titanic,
    mainImage: Assets.images.titanic,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.inception,
    mainImage: Assets.images.inception,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.london,
    mainImage: Assets.images.london,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.frontCover,
    mainImage: Assets.images.frontCover,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.titanic,
    mainImage: Assets.images.titanic,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.inception,
    mainImage: Assets.images.inception,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.london,
    mainImage: Assets.images.london,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.frontCover,
    mainImage: Assets.images.frontCover,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];
List<MovieModel> childrenCartoons = [
  MovieModel(
    bgImage: Assets.images.titanic,
    mainImage: Assets.images.titanic,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.sing,
    mainImage: Assets.images.sing,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mermaidCartoon,
    mainImage: Assets.images.mermaidCartoon,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.frozen,
    mainImage: Assets.images.frozen,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.bigAndSmall,
    mainImage: Assets.images.bigAndSmall,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.moana,
    mainImage: Assets.images.moana,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.titanic,
    mainImage: Assets.images.titanic,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.sing,
    mainImage: Assets.images.sing,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.mermaidCartoon,
    mainImage: Assets.images.mermaidCartoon,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.frozen,
    mainImage: Assets.images.frozen,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.bigAndSmall,
    mainImage: Assets.images.bigAndSmall,
    name: "Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
  MovieModel(
    bgImage: Assets.images.moana,
    mainImage: Assets.images.moana,
    name: "Last Christmas",
    genre: "2022 фантастика, фэнтези, боевик, приключения",
    about: "",
    rating: "IMDB 8.6",
  ),
];
